<a href="https://colab.research.google.com/github/RafalMarcinkiewicz/DataScienceBootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.25.2'

1D array

In [ ]:
x = np.array([3, 5])
x

array([3, 5])

In [ ]:
print(x)

[3 5]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

2D Array

In [ ]:
x = np.array([1.2, 8.4, 6.2])
print(x)

[1.2 8.4 6.2]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.array([[1, 2], [-3, 6]])
x

array([[ 1,  2],
       [-3,  6]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 4, 5], [3, 8, 5]])
x

array([[1, 4, 5],
       [3, 8, 5]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[1, 4, 5], [3, 8, 5]],

     [[9, 6, 3], [2, 6, 9]]])
x

array([[[1, 4, 5],
        [3, 8, 5]],

       [[9, 6, 3],
        [2, 6, 9]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

Typy danych

In [3]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [4]:
A = np.array([1.4, 2.0, 3.2])
A.dtype

dtype('float64')

In [5]:
A = np.array([1, 2, 3], dtype="float")
A.dtype

dtype('float64')

In [6]:
A = np.array([1, 2, 3], dtype="complex")
A.dtype

dtype('complex128')

In [7]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

Tworzenie tablic

In [5]:
np.zeros(shape=[4, 10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones(shape=[5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full(shape=[3, 3], fill_value=4, dtype=int)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [12]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [14]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [16]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [19]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
A.reshape((5, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [24]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje na tablicach

In [25]:
A = np.array([1, 2, 3, 4])
B = np.array([2, -1, 3, 8])
print(A)
print(B)

[1 2 3 4]
[ 2 -1  3  8]


In [32]:
np.add(A, B)

array([ 3,  1,  6, 12])

In [27]:
A + B

array([ 3,  1,  6, 12])

In [33]:
np.subtract(A, B)

array([-1,  3,  0, -4])

In [28]:
A - B

array([-1,  3,  0, -4])

In [34]:
np.multiply(A, B)

array([ 2, -2,  9, 32])

In [29]:
A * B

array([ 2, -2,  9, 32])

In [35]:
np.divide(A, B)

array([ 0.5, -2. ,  1. ,  0.5])

In [30]:
A / B

array([ 0.5, -2. ,  1. ,  0.5])

In [31]:
A +3*B

array([ 7, -1, 12, 28])

In [44]:
x = np.array([[1, 2], [-2, 0]])
y = np.array([[6, 0], [-1, 2]])
print(x)

print(y)

[[ 1  2]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [40]:
np.dot(x, y)

array([[  4,   4],
       [-12,   0]])

In [41]:
x.dot(y)

array([[  4,   4],
       [-12,   0]])

In [42]:
y.dot(x)

array([[ 6, 12],
       [-5, -2]])

In [46]:
x @ y

array([[  4,   4],
       [-12,   0]])

Gnenerowanie liczb pseudolosowych

In [47]:
np.random.seed(0)

In [51]:
np.random.randn(10, 4)

array([[-0.89546656,  0.3869025 , -0.51080514, -1.18063218],
       [-0.02818223,  0.42833187,  0.06651722,  0.3024719 ],
       [-0.63432209, -0.36274117, -0.67246045, -0.35955316],
       [-0.81314628, -1.7262826 ,  0.17742614, -0.40178094],
       [-1.63019835,  0.46278226, -0.90729836,  0.0519454 ],
       [ 0.72909056,  0.12898291,  1.13940068, -1.23482582],
       [ 0.40234164, -0.68481009, -0.87079715, -0.57884966],
       [-0.31155253,  0.05616534, -1.16514984,  0.90082649],
       [ 0.46566244, -1.53624369,  1.48825219,  1.89588918],
       [ 1.17877957, -0.17992484, -1.07075262,  1.05445173]])

In [53]:
np.random.rand(10, 3)

array([[0.42385505, 0.60639321, 0.0191932 ],
       [0.30157482, 0.66017354, 0.29007761],
       [0.61801543, 0.4287687 , 0.13547406],
       [0.29828233, 0.56996491, 0.59087276],
       [0.57432525, 0.65320082, 0.65210327],
       [0.43141844, 0.8965466 , 0.36756187],
       [0.43586493, 0.89192336, 0.80619399],
       [0.70388858, 0.10022689, 0.91948261],
       [0.7142413 , 0.99884701, 0.1494483 ],
       [0.86812606, 0.16249293, 0.61555956]])

In [57]:
np.random.randint(low=10, high=101, size=10)

array([56, 30, 63, 39, 77, 45, 49, 19, 83, 51])

In [67]:
np.random.choice([4, 1, 3, 2])

3

In [75]:
np.random.choice(["python", "java", "sql"])


'python'

In [76]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.random.shuffle(data)
data

array([9, 2, 0, 3, 8, 1, 5, 4, 6, 7])

Podstawowe funkcje

In [79]:
np.exp(1)

2.718281828459045

In [80]:
np.sqrt(9)

3.0

In [81]:
np.all([1, 2, 3])

True

In [82]:
np.all([1, 3, 0])

False

In [83]:
np.any([0, 0, 0])

False

In [84]:
np.any([0, 1, 0])

True

In [85]:
bool(0)

False

In [86]:
bool(3)

True

In [88]:
A = np.random.rand(10)
A

array([0.57722859, 0.23789282, 0.934214  , 0.61396596, 0.5356328 ,
       0.58990998, 0.73012203, 0.311945  , 0.39822106, 0.20984375])

In [89]:
np.argmax(A)

2

In [90]:
A[np.argmax(A)]

0.9342139979247938

In [91]:
np.argmin(A)

9

In [92]:
np.argsort(A)

array([9, 1, 7, 8, 4, 0, 5, 3, 6, 2])

In [93]:
np.max(A)

0.9342139979247938

In [94]:
np.min(A)

0.20984374897512215

In [95]:
np.mean(A)

0.5138975979436481

In [96]:
np.median(A)

0.556430695814563

In [97]:
np.std(A)

0.2159830934797071

Indeksowanie, wycinanie

In [3]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
b = a[2]
c = a[4:]
d = a[:7]
e = a[[3, 8]]

print("b: ")
print(b)
print("c: ")
print(c)
print("d: ")
print(d)
print("e: ")
print(e)

b: 
2
c: 
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
d: 
[0 1 2 3 4 5 6]
e: 
[3 8]


In [11]:
a = a.reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
a[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [9]:
a[1, 2] = 14
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [16]:
a
for el in a.flat:
  print(el)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [19]:
a.shape

(4, 5)

In [20]:
a.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

transponowanie - zamiana wiersza z kolumną

In [23]:
a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [29]:
a = np.arange(start = -10, stop = 10, step = 0.5)
a = a.reshape(10, -1)
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [26]:
a > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
a[a>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [30]:
np.bitwise_and(a > -5, a < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])