<a href="https://colab.research.google.com/github/RafalMarcinkiewicz/DataScienceBootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Norma wektora, długość wektora w R^2

In [1]:
import numpy as np

In [2]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [3]:
np.linalg.norm(v1)

4.0

In [4]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [5]:
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p - q)

5.0

In [7]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p - q)

5.0990195135927845

Mnożenie macierzy

In [9]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, "\n")
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [12]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [13]:
Z.shape

(2, 1)

In [14]:
X = np.array([[2, -1, 3], [3, 1, 0]])
Y = np.array([[2, 1, -1], [0, -1, 2], [3, 2, 0]])
print(X,"\n")
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [16]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [17]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

Ślad macierzy - suma elementów na przekątnej

In [19]:
A = np.array([[2, 4], [-1, 3]])
A
np.trace(A)


5

Macierz jednostkowa - jedynki na przekątnej a pozostałe zera

In [21]:
np.eye(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

In [25]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [30]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [31]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana - zamiana wierszy z kolumnami

In [32]:
C = np.transpose(A)
C

array([[ 2, -1],
       [ 4,  3]])

In [33]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [36]:
A = np.array([[2, 4], [1, -1]])
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [39]:
AInv = np.linalg.inv(A)
X = np.dot(AInv, B)
X

array([[1.],
       [2.]])